### ISSUE TITLE
port?

### ISSUE THREAD

**Issue by JMarceloCasanova** [plusk01/roboclaw-v5#1]
AttributeError: Roboclaw instance has no attribute '_port'

When using this library on a v3 it outputs the error above, using a raspberrypi, i've tried with both tx from GPIO and UART (usb to ttl), the os is stretch lite.

**Comment by plusk01** [comment]
This is the v5 repo -- are you aware of the [roboclaw-v3](https://github.com/plusk01/roboclaw-v3) repo? Are you using Python 2.7?

If you still get the error after making sure you are using the right version, post a small, relevant code snippet that captures what you are trying to do and the error you are seeing.

Also, this (and the version 3 library) were used in [this](https://github.com/zamora18/robot-soccer/blob/develop/ros/src/playground/nodes/motion/wheelbase.py#L132) project, which might shine some light on the problem.

**Comment by JMarceloCasanova** [comment]
Yes, I’m using python 2.7, however I was using the version 5 instead, I’m not sure if the problem is with me but when I clicked in the GitHub link (“here”) for the v3 it sent me to the same page so i assumed it was the same.

Thank you very much for the fast reply.

wanna_be_fast TEAM
No dia 09/02/2018, às 14:42, Parker Lusk <notifications@github.com<mailto:notifications@github.com>> escreveu:

this<https://github.com/zamora18/robot-soccer/blob/develop/ros/src/playground/nodes/motion/wheelbase.py#L132>

**Comment by plusk01** [comment]
Definitely my issue, thanks for pointing it out!
